<a href="https://colab.research.google.com/github/shinchacoffee/pytorch_basics_1/blob/main/tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import numpy as np

In [2]:
data = [[1, 2], [3, 4]]
data_tens = torch.tensor(data)
data_ndar = np.array(data)
data_tens_from_ndar = torch.tensor(data_ndar)
print(f"{data}\n{data_ndar}\n{data_tens}\n{data_tens_from_ndar}")

[[1, 2], [3, 4]]
[[1 2]
 [3 4]]
tensor([[1, 2],
        [3, 4]])
tensor([[1, 2],
        [3, 4]])


In [3]:
#from torch._C import dtype
tensor_ones = torch.ones_like(data_tens)
#tensor_rand1 = torch.rand_like(data_tens) #-> gets error that not defined/works for long type...
tensor_rand2 = torch.rand_like(data_tens, dtype=torch.float)
print(f"{tensor_ones}\n{tensor_rand2}")

tensor([[1, 1],
        [1, 1]])
tensor([[0.4755, 0.1494],
        [0.3518, 0.2336]])


In [4]:
shape1 = (2,3,)
shape2 = (2,3)
ones_tensor = torch.ones(shape1)
rand_tensor = torch.rand(shape2)
print(f"{ones_tensor}\n{rand_tensor}, {ones_tensor.shape}, {rand_tensor.shape}")

tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[0.5067, 0.3278, 0.3004],
        [0.4985, 0.9265, 0.3598]]), torch.Size([2, 3]), torch.Size([2, 3])


In [5]:
tensor = torch.rand(2,3)
print(f"tensor shape: {tensor.shape}")
print(f"tensor data type: {tensor.dtype}")
print(f"tensor is on device: {tensor.device}")

tensor shape: torch.Size([2, 3])
tensor data type: torch.float32
tensor is on device: cpu


In [10]:
tensor = tensor.to("cpu")
device = "cuda" if torch.cuda.is_available() else "cpu"
print(f"will be using device: {device}")
tensor.to(device)
print(f"tensor is on device: {tensor.device}")
tensor = tensor.to(device)
print(f"tensor is on device: {tensor.device}")

will be using device: cuda
tensor is on device: cpu
tensor is on device: cuda:0


In [30]:
tensor = torch.rand(4,4)
print(tensor)
print(f"first row: {tensor[0,:]}")
print(f"first column: {tensor[:,0]}")
print(f"last column: {tensor[...,-1]}")
print(f"some part: {tensor[:-2,2:]}")
print(f"some part: {tensor[1:-1,1:-1]}") #so interval is closed at the begining and open at the end

tensor([[0.5497, 0.3987, 0.0496, 0.8763],
        [0.6967, 0.8483, 0.2954, 0.6611],
        [0.1146, 0.3983, 0.1336, 0.0251],
        [0.8321, 0.2768, 0.3731, 0.3879]])
first row: tensor([0.5497, 0.3987, 0.0496, 0.8763])
first column: tensor([0.5497, 0.6967, 0.1146, 0.8321])
last column: tensor([0.8763, 0.6611, 0.0251, 0.3879])
some part: tensor([[0.0496, 0.8763],
        [0.2954, 0.6611]])
some part: tensor([[0.8483, 0.2954],
        [0.3983, 0.1336]])


In [45]:
tensor = torch.rand(2,2)
tensor[:,1]=0
joined = torch.concat([tensor, tensor, tensor], dim=1)
print(joined)
joined2 = torch.concat([tensor, tensor, tensor], dim=0)
print(joined2)
joined3 = torch.concat([tensor, tensor, tensor], dim=-1)
print(joined3)
joined4 = torch.concat([tensor, tensor, tensor], dim=-2)
print(joined4)

tensor([[0.2982, 0.0000, 0.2982, 0.0000, 0.2982, 0.0000],
        [0.1576, 0.0000, 0.1576, 0.0000, 0.1576, 0.0000]])
tensor([[0.2982, 0.0000],
        [0.1576, 0.0000],
        [0.2982, 0.0000],
        [0.1576, 0.0000],
        [0.2982, 0.0000],
        [0.1576, 0.0000]])
tensor([[0.2982, 0.0000, 0.2982, 0.0000, 0.2982, 0.0000],
        [0.1576, 0.0000, 0.1576, 0.0000, 0.1576, 0.0000]])
tensor([[0.2982, 0.0000],
        [0.1576, 0.0000],
        [0.2982, 0.0000],
        [0.1576, 0.0000],
        [0.2982, 0.0000],
        [0.1576, 0.0000]])


In [49]:
y1 = tensor @ tensor.T
y2 = tensor.matmul(tensor.T)
y3 = torch.rand_like(tensor)
torch.matmul(tensor, tensor.T, out=y3)
print(tensor)
print(f"{y1}\n{y2}\n{y3}")
z1 = tensor * tensor
z2 = tensor.mul(tensor)
z3 = torch.rand_like(tensor)
torch.mul(tensor, tensor, out=z3)
print(tensor)
print(f"{z1}\n{z2}\n{z3}")

tensor([[0.2982, 0.0000],
        [0.1576, 0.0000]])
tensor([[0.0889, 0.0470],
        [0.0470, 0.0249]])
tensor([[0.0889, 0.0470],
        [0.0470, 0.0249]])
tensor([[0.0889, 0.0470],
        [0.0470, 0.0249]])
tensor([[0.2982, 0.0000],
        [0.1576, 0.0000]])
tensor([[0.0889, 0.0000],
        [0.0249, 0.0000]])
tensor([[0.0889, 0.0000],
        [0.0249, 0.0000]])
tensor([[0.0889, 0.0000],
        [0.0249, 0.0000]])


In [51]:
agg = tensor.sum()
agg_item = agg.item()
print(f"{tensor}, {agg_item}, {type(agg_item)}")

tensor([[0.2982, 0.0000],
        [0.1576, 0.0000]]), 0.4558658003807068, <class 'float'>


In [52]:
print(tensor)
tensor.add_(2)
print(tensor)

tensor([[0.2982, 0.0000],
        [0.1576, 0.0000]])
tensor([[2.2982, 2.0000],
        [2.1576, 2.0000]])


In [53]:
tt = torch.ones(3)
nn = tt.numpy()
print(tt,nn)

tensor([1., 1., 1.]) [1. 1. 1.]


In [56]:
tt.add_(1)
print(tt,nn)

tensor([2., 2., 2.]) [2. 2. 2.]


In [57]:
n = np.ones(4)
t = torch.from_numpy(n)
print(t,n)
np.add(n, 1, out=n)
print(f"t: {t}")
print(f"n: {n}")

tensor([1., 1., 1., 1.], dtype=torch.float64) [1. 1. 1. 1.]
t: tensor([2., 2., 2., 2.], dtype=torch.float64)
n: [2. 2. 2. 2.]
